openapi: "3.0.0"
info:
  title: "Vanilla Instagram APIs"
  description: >
    3ì¸ ê°œë°œ ì„œë¹„ìŠ¤ì˜ API ë¬¸ì„œì™€ í…ŒìŠ¤íŠ¸ë¥¼ ìœ„í•´ ì‘ì„±ëœ ë¬¸ì„œì…ë‹ˆë‹¤.
  version: "1.0.0"

servers:
  - url: "http://localhost:8001/api"
    description: "ê°œë°œ ì „ìš© ì„œë²„"

tags:
  - name: SMS API
    description: â£ SMS ì„œë¹„ìŠ¤ì— ê´€í•œ API
  - name: ì‚¬ìš©ì API
    description: ğŸ˜ ì‚¬ìš©ìì— ê´€í•œ API
  - name: í…ŒìŠ¤íŠ¸ API
    description: âš  í…ŒìŠ¤íŠ¸ë¥¼ ìœ„í•œ API

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: "ì„¸ì…˜ ì •ë³´"

paths:
  /user:
    post:
      summary: "íšŒì›ê°€ì… API"
      description: "ì¸ì¦ ì—¬ë¶€ë¥¼ ê²€ì‚¬í•˜ê³  íšŒì›ê°€ì…ì„ ìˆ˜í–‰í•©ë‹ˆë‹¤."
      tags:
        - ì‚¬ìš©ì API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              phoneNumber: "01011112222"
              realname: "name"
              username: "name"
              password: "password"
      responses:
        201:
          description: "íšŒì›ê°€ì… ì™„ë£Œ"
          content:
            application/json:
              schema:
                type: object
              example:
                message: "íšŒì›ê°€ì…ì´ ì™„ë£Œë˜ì—ˆìŠµë‹ˆë‹¤"
        401:
          description: "ë²ˆí˜¸ ì¸ì¦ì´ ë˜ì§€ ì•ŠìŒ"
        409:
          description: "ìœ ì €ê°€ ì´ë¯¸ ì¡´ì¬í•¨"
        400:
          description: "ìš”ì²­ í¼ì´ ì˜ëª» ë˜ì—ˆê±°ë‚˜, ì¸ì¦ìƒíƒœì—ì„œ ì ‘ê·¼ ë¨"

  /user/{username}/exist:
    get:
      tags:
        - ì‚¬ìš©ì API
      summary: "ìœ ì €ë„¤ì„ ê²€ì¦ API"
      description: "ì‚¬ìš©ê°€ëŠ¥í•œ ìœ ì € ì´ë¦„ì¸ ì§€ ê²€ì‚¬í•©ë‹ˆë‹¤."
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: "íšŒì›ê°€ì…ì— ì‚¬ìš© ë  ì´ë¦„"
      responses:
        202:
          description: "ì‚¬ìš© ê°€ëŠ¥í•œ ì´ë¦„"
          content:
            application/json:
              schema:
                type: object
              example:
                status: 202
                message: "ì‚¬ìš© ê°€ëŠ¥í•œ username ì…ë‹ˆë‹¤."
        409:
          description: "ì‚¬ìš©ì¤‘ì¸ ì´ë¦„"
          content:
            application/json:
              schema:
                type: object
              example:
                message: "ì´ë¯¸ ì¡´ì¬í•˜ëŠ” username ì…ë‹ˆë‹¤."
  /sms:
    post:
      summary: "ì¸ì¦ ì½”ë“œ ë°œì†¡ API"
      description: "í° ë²ˆí˜¸ë¥¼ ë°›ì•„ì„œ íšŒì›ê°€ì… ì¸ì¦ì½”ë“œë¥¼ ë°œì†¡í•©ë‹ˆë‹¤"
      tags:
        - SMS API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              phoneNumber: "01011112222"
      responses:
        200:
          description: "ì¸ì¦ë²ˆí˜¸ ì „ì†¡ ì™„ë£Œ"
          content:
            application/json:
              schema:
                type: obejct
              example:
                message: "01011112222 ë²ˆí˜¸ë¡œ ì¸ì¦ë²ˆí˜¸ê°€ ì „ì†¡ë˜ì—ˆìŠµë‹ˆë‹¤."
                data:
                  maxAge: 493294
        400:
          description: "ìœ íš¨í•˜ì§€ ì•Šì€ ì „í™”ë²ˆí˜¸ ë˜ëŠ” ìš”ì²­ í¼ì´ ì˜ëª»ë˜ì—ˆìŒ"

  /sms/match:
    post:
      summary: "ì¸ì¦ì½”ë“œ ì¸ì¦ API"
      description: "íšŒì›ê°€ì… ìˆ˜í–‰ ì „, ì½”ë“œë¥¼ ì…ë ¥ë°›ì•„ì„œ ë°œì†¡ëœ ì •ë³´ì™€ ì¼ì¹˜í•˜ëŠ” ì§€ ê²€ì‚¬í•©ë‹ˆë‹¤."
      tags:
        - SMS API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              phoneNumber: "01011112222"
              code: 10101
      responses:
        202:
          description: "ì¸ì¦ë²ˆí˜¸ í™•ì¸ ì„±ê³µ"
          content:
            application/json:
              schema:
                type: obejct
              example:
                message: "ì¸ì¦ë²ˆí˜¸ í™•ì¸ ì™„ë£Œ."
        400:
          description: "ì˜ëª»ëœ ì¸ì¦ë²ˆí˜¸"
        410:
          description: "ì¸ì¦ ë²ˆí˜¸ ë§Œë£Œ ë˜ëŠ” ì¡´ì¬í•˜ì§€ ì•Šì€ ì¸ì¦ ì •ë³´"
